name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo apt update
        sudo apt install debhelper dpkg-dev -y
    - name: package
      run: |
        dpkg-buildpackage -us -uc
