name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo apt update
        sudo apt install debhelper dpkg-dev -y
    - name: package
      run: |
        mkdir -p tmp
        cd tmp && \
        ln -s ../fwupd-wrapper ../debian . && \
        dpkg-buildpackage -us -uc
    - name: Capture artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debian package
        path: |
          *.deb
